# 基本設置
owner: kaobar00124 # Your GitHub organization or username, where this repository lives
repo: StatusPage # The name of this repository

# 更新間隔時間
delay: 30000

# 檢測內容
sites:
  - name: "主要服務平台 | Main service platforms"
    url: https://kaobar.godofsoul.com
    slug: kaobar-main

# 狀態頁面設置
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  name: 會考霸｜服務狀態
  cname: status.kaobar.godofsoul.com
  # baseUrl: /StatusPage
  introTitle: "會考霸 服務狀態"
  # introMessage: ""
  themeUrl: https://status.kaobar.godofsoul.com/theme.css
  logoUrl: https://cdn.kaobar.godofsoul.com/Logo.png
  favicon: https://cdn.kaobar.godofsoul.com/Logo.png
  customHeadHtml: <!-- HTML Meta Tags -->
    <meta name="description" content="會考霸的服務狀態頁面">

    <!-- Facebook Meta Tags -->
    <meta property="og:url" content="https://kaobar.godofsoul.com/">
    <meta property="og:type" content="website">
    <meta property="og:title" content="會考霸服務狀態">
    <meta property="og:description" content="會考霸的服務狀態頁面">
    <meta property="og:image" content="https://cdn.kaobar.godofsoul.com/Logo.png">

    <!-- Twitter Meta Tags -->
    <meta name="twitter:card" content="summary_large_image">
    <meta property="twitter:domain" content="kaobar.godofsoul.com">
    <meta property="twitter:url" content="https://kaobar.godofsoul.com/">
    <meta name="twitter:title" content="會考霸服務狀態">
    <meta name="twitter:description" content="會考霸的服務狀態頁面">
    <meta name="twitter:image" content="https://cdn.kaobar.godofsoul.com/Logo.png">

    <!-- Apple Web App -->
    <meta name="format-detection" content="telephone=no">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-title" content="會考霸服務狀態">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">

    <meta name="author" content="會考霸服務狀態－築夢之地團隊">
    <link rel="author" href="https://kaobar.godofsoul.com">
  customBodyHtml: "<!-- Custom HTML to add at the beginning of <body> -->"


#i18n
i18n:
  activeIncidents: 當前事件
  allSystemsOperational: 所有系統運行正常
  incidentReport: "事件 #$NUMBER 報告 →"
  activeIncidentSummary: 開啟於 $DATE，共有 $POSTS 則貼文
  incidentTitle: 事件 $NUMBER 詳情
  incidentDetails: 事件詳情
  incidentFixed: 已修復
  incidentOngoing: 進行中
  incidentOpenedAt: 開啟於
  incidentClosedAt: 關閉於
  incidentViewOnGitHub: 在 GitHub 上查看並訂閱
  incidentCommentSummary: 於 $DATE 由 $AUTHOR 發表
  incidentBack: ← 返回所有事件
  pastIncidents: 過去事件
  pastIncidentsResolved: 於 $MINUTES 分鐘內解決，共有 $POSTS 則貼文
  liveStatus: 即時狀態
  overallUptime: "總運行時間：$UPTIME"
  overallUptimeTitle: 總運行時間
  averageResponseTime: "平均回應時間：$TIMEms"
  averageResponseTimeTitle: 平均回應時間
  sevelDayResponseTime: 7 天回應時間
  responseTimeMs: 回應時間 (毫秒)
  up: 正常運行
  down: 停止運行
  degraded: 降級運行
  ms: 毫秒
  loading: 載入中
  navGitHub: GitHub
  footer: "本頁面由 Novainit Studio 協助建置。使用 Upptime 系統"
  rateLimitExceededTitle: 超過速率限制
  rateLimitExceededIntro: 您已超過每小時請求的次數，請等待一段時間後再試。或者，您可以新增 GitHub 個人存取令牌繼續使用此網站。
  rateLimitExceededWhatDoesErrorMean: 這個錯誤意味著什麼？
  rateLimitExceededErrorMeaning: 此網站使用 GitHub API 來取得網站狀態的即時數據。預設情況下，GitHub 允許每個 IP 地址每小時最多 60 次請求，您已經達到這個上限。
  rateLimitExceededErrorHowCanFix: 如何解決？
  rateLimitExceededErrorFix: 您可以等待一小時，您的 IP 地址的請求限制將恢復。或者，您可以新增 GitHub 個人存取令牌，這樣您每小時會有額外的 5000 次請求限制。
  rateLimitExceededGeneratePAT: 了解如何生成個人存取令牌
  rateLimitExceededHasSet: 您已設置個人存取令牌。
  rateLimitExceededRemoveToken: 移除令牌
  rateLimitExceededGitHubPAT: GitHub 個人存取令牌
  rateLimitExceededCopyPastePAT: 複製並粘貼您的令牌
  rateLimitExceededSaveToken: 保存令牌
  errorTitle: 發生錯誤
  errorIntro: 嘗試獲取最新狀態詳情時發生錯誤。
  errorText: 您可以稍後再試。
  errorHome: 前往首頁
  pastScheduledMaintenance: 過去的預定維護
  scheduledMaintenance: 預定維護
  scheduledMaintenanceSummaryStarted: 於 $DATE 開始，持續 $DURATION 分鐘
  scheduledMaintenanceSummaryStarts: 於 $DATE 開始，持續 $DURATION 分鐘
  startedAt: 開始於
  startsAt: 開始於
  duration: 持續時間
  durationMin: $DURATION 分鐘
  incidentCompleted: 完成
  incidentScheduled: 預定
  duration24H: 24小時
  duration7D: 7天
  duration30D: 30天
  duration1Y: 1年
  durationAll: 所有
  locale: zh-TW
  # navbar:
  #  - title: Status
  #    href: /
  #  - title: GitHub
  #    href: https://github.com/$OWNER/$REPO

